### ISSUE TITLE
Not scraping emails?

### ISSUE THREAD

**Issue by tzUNC** [rayane-b/linkedin_webscraper#1]
Hi, I'm trying to use this. It gives me all info *except* emails. Not sure why. I see the email popup in chrome when it's running but it says nothing found in terminal. Any thoughts?

**Comment by rbouaf** [comment]
Hi!
Thanks for pointing that out.
LinkedIn updated their website. 
I updated the code to fix this problem.
I changed a single line of code (line 125)

Thanks again!

**Comment by tzUNC** [comment]
Thanks for fixing that! I'm trying to scrape ~5000 emails from my connections but the issue is that it keeps stopping after around 50. Is there any quick fix for that maybe?

**Comment by rbouaf** [comment]
Hey! 
I can think of why it's happening. 
Linkedin probably doesn't load all 5000 connections all at once and loads them 50 at a time.
I only have 5 connections so fixing this issue might be slightly harder than usual.
I came up with a quick fix. I'll have the program scroll down all the way down to the bottom of the page.
I updated the code to fix this problem. 
Only a few lines of code were changed (lines 75 to 81)

I can't test the code myself because as I said, I only have 5 connections.
Please post in this thread again if the problem persists.

Thank you.

**Comment by tzUNC** [comment]
So this GIVE_TIME_TO_LOAD variable is what I'm out changing. I think however that it will scroll down, give time to load, and then run whereas it needs to scroll, load, scroll more, load, etc, until it can't be scrolled anymore? Does that make sense?

**Comment by tzUNC** [comment]
I'm trying just doing a for loop 200 times to load the page over and over. Will run overnight and see if it works. Thanks for being receptive to changes!!

**Comment by tzUNC** [comment]
Now I'm getting the clicking error - element click intercepted: Element <a data-control-name="contact_see_more" href="/in/frankwintrich/detail/contact-info/" id="ember114" class="active ember-view">...</a> is not clickable at point (226, 460). Other element would receive the click: <div aria-hidden="false" id="ember160" class="artdeco-modal-overlay artdeco-modal-overlay--layer-default artdeco-modal-overlay--is-top-layer  ember-view">...</div>
  (Session info: chrome=86.0.4240.111)

**Comment by rbouaf** [comment]
Hi,
This is hard for me to fix quickly because I can't actually test the changes I make to the code.
I'm not sure how the click error happened. 
I will try a totally different approach.
I have updated the code once again.
I have changed lines 75 to 82
Please post in this thread again if the problem persists.

Thank you.

**Comment by tzUNC** [comment]
I think I fixed that issue by commenting out the clicks and doing this:
#contact_info.click()
#contact_info.click()
#contact_info.click() #sometimes it doesn't click right away, so I got frustrated while writing the code.
driver.execute_script("arguments[0].click();", contact_info)

I’m now getting a none type error on some random names but I also added and ifs else to check if name is none type first. Will run at night and see if it works.

On Oct 26, 2020, at 1:15 PM, rayane-b <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,
This is hard for me to fix quickly because I can't actually test the changes I make to the code.
I'm not sure how the click error happened.
I will try a totally different approach.
I have updated the code once again.
I have changed lines 75 to 82
Please post in this thread again if the problem persists.

Thank you.

**Comment by rbouaf** [comment]
Hi,
I think you should leave at least one click, that might be important. 
But if it works fine then alright.

Thank you
